### PR TITLE
[WFLY-14822] Additional PostBuild tests for the archetypes

### PR DESCRIPTION
**Pull request by WolfgangHG**
Fixes [https://issues.redhat.com/browse/WFLY-14821](https://issues.redhat.com/browse/WFLY-14822)

### CODE REVIEW

**Comment by boris-unckel** [comment]
@WolfgangHG I have created a Jira issue for your work. You have to change the commit message to 
[WFLY-14821] Additional PostBuild tests for the archetypes <--- title of the commit
Fixes https://issues.redhat.com/browse/WFLY-14821 <-- body message of the commit

**Comment by WolfgangHG** [comment]
I made some changes and hopefully did the correct thing ;-). Sorry, I am a newbie to Git.

**Comment by boris-unckel** [comment]
Try locally with 'git commit --amend' and then 'git push --force origin master'
You didn't setup a branch but commited directly to master - try to avoid that in the future. (git checkout -b myNewBranch)

**Comment by emmartins** [comment]
@WolfgangHG  @boris-unckel hi, WFLY-14821 seems unrelated to this change, is that the correct JIRA?

**Comment by boris-unckel** [comment]
@WolfgangHG Hello Wolfgang, @emmartins is right. My apologies posting the wrong link. The correct one is [https://issues.redhat.com/browse/WFLY-14822](https://issues.redhat.com/browse/WFLY-14822) "WildFly Maven archetypes: Additional PostBuild tests". Wolfgang could you please change this in the commit message (git command see above) and in the pull request?

**Comment by WolfgangHG** [comment]
@boris-unckel  done - hope it is OK now ;-)

**Pull request merged**
