### PR TITLE
[WFLY-15051]

### PR DESCRIPTION
**Pull request by emmartins**
Issue: https://issues.redhat.com/browse/WFLY-15051
Superseeds #21

### CODE REVIEW

**Comment by emmartins** [comment]
@WolfgangHG can you please confirm those are the intended changes on #21?

**Comment by WolfgangHG** [comment]
@emmartins Yes, I checked out this pull request and don't see any file differences compared to the my original files.

**Comment by emmartins** [comment]
@WolfgangHG ok, just made a fix in the README.adoc (archetype artifact Id is wildfly-subsystem, not wildfly-subsystem-archetype) and squashed all changes into a single commit. Thanks for this extra contribution :-)

**Comment by emmartins** [comment]
release, thanks again

**Pull request merged**
