### PR TITLE
Update EAR archetype

### PR DESCRIPTION
**Pull request by jmesnil**
Use web, ejb and ear as the name of the modules

Their artifactIds are not changed.

### CODE REVIEW

**Comment by WolfgangHG** [comment]
I am not sure about this. This would result in a file "web.war", wouldn't it? If it is deployed, the web application would be found at "localhost:8080/web". This could will cause trouble if the user generates two testing apps from the archetype and deploys both.

Currently, the "finalName" is declared this way (maven property):
`<finalName>${project.artifactId}</finalName>`

I don't have time to test it now, but would it work to change this name to a reference to "rootArtifactId" (archetype property)?
Similarly, we could change the name of the EAR and EJB file.

What do you think?

**Comment by jmesnil** [comment]
@WolfgangHG this PR does not change any `artifactId`. The war would still be called eg `multi-web.war`.

I'm only changing the name of the *folders*. Instead of having `multi/multi-web/pom.xml`, you would now have `multi/web/pom.xml`.
If you look at the CI, you can see what's going on:

```
...
[INFO] Building jar: /home/runner/work/wildfly-archetypes/wildfly-archetypes/wildfly-jakartaee-ear-archetype/testing/arq-managed/multi/ejb/target/multi-ejb.jar
...
[INFO] Building war: /home/runner/work/wildfly-archetypes/wildfly-archetypes/wildfly-jakartaee-ear-archetype/testing/arq-managed/multi/web/target/multi-web.war
...
[INFO] Building ear: /home/runner/work/wildfly-archetypes/wildfly-archetypes/wildfly-jakartaee-ear-archetype/testing/arq-remote/multi/ear/target/multi.ear
...
```

Before that PR, the logs would have been:

```
...
[INFO] Building jar: /home/runner/work/wildfly-archetypes/wildfly-archetypes/wildfly-jakartaee-ear-archetype/testing/arq-managed/multi/multi-ejb/target/multi-ejb.jar
...
[INFO] Building war: /home/runner/work/wildfly-archetypes/wildfly-archetypes/wildfly-jakartaee-ear-archetype/testing/arq-managed/multi/multi-web/target/multi-web.war
...
[INFO] Building ear: /home/runner/work/wildfly-archetypes/wildfly-archetypes/wildfly-jakartaee-ear-archetype/testing/arq-remote/multi/multi-ear/target/multi.ear
...
```

**Comment by WolfgangHG** [comment]
Ok, sorry! Yes, then it is OK to change the directory names. 
How does it look like, when you import the generated project to Eclipse?

**Comment by jmesnil** [comment]
Screenshot 2023-08-17 at 13 27 57

This seems to look good.

**Comment by jmesnil** [comment]
@WolfgangHG thanks!

**Pull request merged**
