### PR TITLE
Update to WildFly 19.0.0.Final, updated all plugin versions, …

### PR DESCRIPTION
**Pull request by WolfgangHG**
…version for maven-compiler-plugin was not used, updated faces-config.xml to 2.3, fixed java warning in test class in webapp archetype

### CODE REVIEW

**Comment by emmartins** [comment]
hi @WolfgangHG, thanks for PR, can you please change it so all POMs versions are SNAPSHOT?We change them as part of the release process. 
Also, did you try the change to 2.3 on faces-config.xml? if I recall it correctly that was before resulting in some issues.

**Comment by WolfgangHG** [comment]
Both done.

@emmartins Yes, you are right, an empty web project causes a deployment error with JSF 2.3:

`Caused by: java.lang.NullPointerException
        at com.sun.faces.facelets.impl.DefaultResourceResolver.resolveUrl(DefaultResourceResolver.java:40)
        at com.sun.faces.facelets.impl.DefaultFaceletFactory.init(DefaultFaceletFactory.java:129)
        at com.sun.faces.application.ApplicationAssociate.createFaceletFactory(ApplicationAssociate.java:849)
        at com.sun.faces.application.ApplicationAssociate.initializeFacelets(ApplicationAssociate.java:342)
        at com.sun.faces.application.ApplicationAssociate.getCompiler(ApplicationAssociate.java:420)
        at com.sun.faces.config.processor.FaceletTaglibConfigProcessor.process(FaceletTaglibConfigProcessor.java:217)
        at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:341)
        ... 23 more`

Adding an empty "beans.xml" (or any CDI annotated class) fixed this. And the error does not occur with JSF 2.2.
I remember having the same issue when initially creating the archetype. I thought it was fixed in WildFly since then because I could not reproduce it after you merged my pull request. But  I did not notice that this was fixed because you (?) downgraded JSF to 2.2 ;-).

I added a note to "faces-config.xml" of the web archetype. The EAR project does not raise this error, but I set it to 2.2, too.

Do you think this deployment error should be reported somewhere? If yes: at which project?

**Comment by emmartins** [comment]
2.3 probably requires CDI yet the empty deployment doesn't add it automatically? Please report a WFLY JIRA for component JSF

**Comment by WolfgangHG** [comment]
Done: [https://issues.redhat.com/browse/WFLY-13306](https://issues.redhat.com/browse/WFLY-13306)

**Comment by WolfgangHG** [comment]
Just want to remember this pull request ;-)...

**Comment by emmartins** [comment]
@WolfgangHG fyi WildFly Archetypes 19.0.0.Final and 19.1.0.Final released, thanks for your contribution ;-)

**Pull request merged**
