### PR TITLE
[WFLY-15051] Refactored subsystem archetype to be a 'real' archetype, update to WildFly 25

### PR DESCRIPTION
**Pull request by WolfgangHG**
Issue: https://issues.redhat.com/browse/WFLY-15051

### CODE REVIEW

**Comment by emmartins** [comment]
can you please rebase this with master, so the PR doesn't include extra commits?

**Comment by WolfgangHG** [comment]
I tried to follow the steps from [https://gitlab.com/palisade/palisade-release/-/wikis/How-to-rebase-your-branch-from-the-master-branch](https://gitlab.com/palisade/palisade-release/-/wikis/How-to-rebase-your-branch-from-the-master-branch) but I am not sure whether I did the right thing... 
Sorry, I am a git beginner. Next time, I will create real branches for each change.

**Comment by emmartins** [comment]
@WolfgangHG you should have just "git fetch" the remote wildfly repo, and then "git rebase  name_of_the_remote_wildfly_repo/main".

But no worries, I will create a new branch and PR by cherry picking the commits for this change

PS: unless it's a huge change set usually it's good to have a single commit for a PR, and you can achieve this easily by "git rebase -i head~number_of_commits_to_rework", and then in the text editor you may squash multiple commits into one.

**Comment by WolfgangHG** [comment]
Closing, as it was merged as part of #22

**Pull request closed without merging**
